### ISSUE TITLE
Access to my sqs Queue is denied while deploying this .

### ISSUE THREAD

**Issue by ayushthedev** [DanielDaCosta/aws-terraform#1]
``(812f2054-de90-4ab5-a32f-0730ad076f7a)` Endpoint response body before transformations: <?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2009-02-01/"><Error><Type>Sender</Type><Code>AccessDenied</Code><Message>Access to the resource https://sqs.us-east-2.amazonaws.com/apigateway-queue is `denied.</Message><Detail/></Error><RequestId>9c786746-e3ce-51b2-92d5-3099f3bf49b6</RequestId></ErrorResponse>``

**Comment by DanielDaCosta** [comment]
Hello @ayushthedev, thanks for the feedback.

Just checking: you just cloned the repo and executed? or did you do some changes? I'm asking so that I can replicate the error myself

**Comment by ayushthedev** [comment]
My bad I was sending @DanielDaCosta  I was sending `Content-Type:application/x-www-form-urlencoded` as header it was giving me an issue of access denied on my Cloudwatch , when I send `Content-Type:application/json` it just worked fine I wonder what why would that be a case.

**Comment by DanielDaCosta** [comment]
Fine! I'll close this issue since it wasn't a code problem 👍
