### ISSUE TITLE
Add api key and model to validate request body

### ISSUE THREAD

**Issue by yzhanggithub** [DanielDaCosta/aws-terraform#2]
Hi there! First, thank you for the repo, I came across this when I worked on a prototype, very helpful!
I added api key and model to validate the request body, I can do a PR if you accept contributions for this repo, thought I shall ask first.

**Comment by DanielDaCosta** [comment]
Hello!
Glad that it helped you! Sure I would love to receive contributions.

Best Regards

**Comment by yzhanggithub** [comment]
Great! Just sent you the PR.

Best Regards
